### PR TITLE
Allow compile on Delphi 10.3 64bit 

### PR DESCRIPTION
**Pull request by MHumm**
My take on the 64 bit compatibility fix part of the "Couple of small enhancements to JvMemoryDataset and XPButton" pull request #55

### CODE REVIEW

**Comment by MHumm** [comment]
I didn't understand why the ifdef had been deactivated in the original proposal. I changed this to only pull in JvJCLUtils for 64 bit, as at least in Rio WinApi.Windows (which is in interface uses already) already contains this declaration. I hope this is good enough, if not tell me what's not proper yet.

**Comment by obones** [comment]
I have finally had time to install 10.3.1 on my VM with all versions installed, and I have no issue compiling both the JCL and JVCL, both 32 and 64 bits.
So I don't quite understand what's required here.

**Comment by whitehairedgeezer** [comment]
I have JCL3.1 and JVCL 3.6 installed with Rio Community edition.  the 32 bit compile works perfectly.  The 64 bit needs winapi, system and vcl. added to the uses items BUT it falls over in JVThemes as it cant find UxThemes.  Where do I get this from?

**Comment by whitehairedgeezer** [comment]
Please ignore previous message - if you get the search paths correct for 64bit then it compiles ok.  Apologies

**Comment by MHumm** [comment]
@whitehairedgeezer: Does this mean this complete pull request can be closed? Or do we need to do something about it?

**Comment by whitehairedgeezer** [comment]
Close it thanks

**Pull request closed without merging**
