### PR TITLE
JvDBGrid: Removed unnecessary condition 

### PR DESCRIPTION
**Pull request by MHumm**
As requested in the acknowledged Mantis issue 6302
[http://issuetracker.delphi-jedi.org/view.php?id=6302](http://issuetracker.delphi-jedi.org/view.php?id=6302)

### CODE REVIEW

**Comment by obones** [comment]
@ahausladen do you have an opinion on this? The issue reporter suggested to check with you, but it's been so long that I can't remember about this.

**Comment by MHumm** [comment]
@ahausladen "Ping": did you already find the time to look at this one?

**Comment by ahausladen** [comment]
I don't know what that bug report has to do with me. Sure, the code line was "modified" by me in 2006 but only because I changed the line indention with the commit f8d4e5e6b9d85e50d5b297b2b80cf546622a9d58 (try/finally block). So there is no actual relation between me and that line of code.

**Comment by MHumm** [comment]
What's the status of this? The suggestion of the reporter doesn't seem to be really usefull given @ahausladen's comment...

**Comment by ahausladen** [comment]
With the removal of the "(dgIndicator in Options)" the OnTitleArrowMenuEvent that is only available if the indicator is visible can now be triggered by right clicking on the first column. So in order to not trigger that event if no indicator is visible, the check has to be moved to the inner if statement. I will make the commit after merging this.

**Pull request merged**
