### PR TITLE
Fixes AV when using JvInterpreter in 64bit with array

### PR DESCRIPTION
**Pull request by ElminsterAU**

### CODE REVIEW

**Comment by obones** [comment]
Are you sure changing the cast from `NativeInt` to `NativeUInt` is required?
As much as I understand reading a `varInt64` instead of a `varInteger` for a pointer, I don't see the point in changing the type cast, especially because it is immediately cast to a pointer.

**Comment by ElminsterAU** [comment]
When running a 32bit process, on a 64bit version of windows, and having the large address aware flag set, pointers in the 2-4GB range are valid. In that case the request of a varInt64 could, if I'm not mistaken, result in positive values in the 2-4GB range being returned. If NativeInt is a signed 32bit int, that would then result in a range violation. I'm not sure if that NativeInt / NativeUInt cast in between here is needed at all. 

While this changed code seems to work for me for both 64bit and 32bit with large address aware flag, I would very much welcome it if someone else could give this a try too.

**Comment by obones** [comment]
NativeInt and NativeUInt are signed/unsigned and their size is of the targeted platform, hence 32 or 64 bits. 
That's why I believe the cast changes are not needed.
As to the range of memory values, in 64 bits, it goes way over the 4GB limit and so if we "clip" the value to 32 bits, we end up with a totally invalid value. The change to varInt64 is indeed required, but the change of casts should not be.

**Comment by skamradt** [comment]
I believe obones is correct.  There is no real difference between NativeInt and NativeUInt if your casting it to a pointer.  The full 4GB range is still available, it is just represented with negative values if the leftmost bit is set.

**Comment by ElminsterAU** [comment]
The correct typecast in this place is to Int64, not NativeInt, not NativeUInt.

**Pull request merged**
