### PR TITLE
Added UITypes to uses to enable inlining.

### PR DESCRIPTION
**Pull request by MHumm**
Please merge in in order to enable inlining for this unit as well. Added UITypes because I got a compiler warning about it.

### CODE REVIEW

**Comment by obones** [comment]
Just to be sure, it was not enough to place it in the implementation section?

**Comment by MHumm** [comment]
Good point. I hadn't checked to be honest :-(
But I guess it's not sufficient, as afair I looked up how to do it in JvAni.pas and I think there it was in interface section as well as I think the warning is about the class used in some other unit and the compiler needs to see it/have it available in interface section.

**Comment by obones** [comment]
Well, I'm trying to keep the interface uses section at its minimum, so if you could check, that would be great.

**Comment by MHumm** [comment]
Done and changed code. Please merge now.

**Pull request merged**
