### PR TITLE
DSA Dialogs do not scale well in DPI-Aware applications

### PR DESCRIPTION
**Pull request by MHumm**
Implemented layout changes supplied by the creator of this Mantis issue 6633
[http://issuetracker.delphi-jedi.org/view.php?id=6633](http://issuetracker.delphi-jedi.org/view.php?id=6633)

### CODE REVIEW

**Comment by jfudickar** [comment]
With which DPI settings did you have tested it?

**Comment by pyscripter** [comment]
It has been extensively tested as part of PyScripter (https://github.com/pyscripter/pyscripter) with a very wide range of DPI settings (800000 downloads).

**Comment by MHumm** [comment]
While I do believe that you tested your modification with various resolution it might be helpful to provide a simplistic demo project which uses the component (just call that message dialog in some way) and add that as a zip file to the Mantis issue. The maintainers can use this for a short check on their own to be convinced that the quality of the fix is good.

**Comment by jfudickar** [comment]
Hi Markus,
the sample is there. It's in the examples folder only for the dialog component.
I can reproduce the behaviour, but until now I'm not able to get the branch with the modifications onto my comupter. I'm not able to bring TortoriseGit to do it correctly.
Regards
Jens

**Comment by obones** [comment]
Jens, you can get the file here:
https://raw.githubusercontent.com/MHumm/jvcl/Mantis6633_JvDSADialogs_Scale/jvcl/run/JvDSADialogs.pas

**Comment by jfudickar** [comment]
Hi Olivier,
that's fine, but did you know the way to switch my local branch using TortoiseGit to the pull request?
For a single file I can handle it manually, but what happend if there are more changes?
I was not able to figure it out.
Any idea?
Regards
Jens

**Comment by pyscripter** [comment]
http://www.marcusoft.net/2011/01/how-to-apply-pull-request-on-github.html

**Pull request merged**
